
# Site settings
title: CLEλR-C0DE
email: jose.puente@gmail.com
baseurl: "/"
url: "https://www.clear-code.co.uk"
github_username: jose-puente
copyright-notice: Copyright © 2022 Clear Code Ltd.

# Build settings
markdown: kramdown
permalink: /:categories/:slug
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: post
      
